# Generated by Django 4.0 on 2022-01-05 02:46

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211206_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepdf',
            name='nome_arquivo',
        ),
        migrations.AlterField(
            model_name='filepdf',
            name='caminho_arquivo',
            field=models.FileField(upload_to=core.models.caminho_upload),
        ),
        migrations.AlterField(
            model_name='holerite',
            name='mes',
            field=models.CharField(choices=[('Jan', 'Janeiro'), ('Fev', 'Feveiro'), ('Mar', 'Março'), ('Abr', 'Abril'), ('Mai', 'Maio'), ('Jun', 'Junho'), ('Jul', 'Julho'), ('Ago', 'Agosto'), ('Set', 'Setembro'), ('Out', 'Outubro'), ('Nov', 'Novembro'), ('Dez', 'Dezembro')], default='Jan', max_length=4),
        ),
    ]
