# Generated by Django 4.0 on 2022-01-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_filepdf_nome_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='holerite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.holerite'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ponto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ponto'),
        ),
    ]
